{
    "config": {
        "abort": {
            "already_configured": "El dispositiu ja est\u00e0 configurat"
        },
        "error": {
            "cannot_connect": "Ha fallat la connexi\u00f3",
            "invalid_auth": "Autenticaci\u00f3 inv\u00e0lida",
            "unknown": "Error inesperat"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Amfitri\u00f3",
                    "password": "Contrasenya",
                    "username": "Nom d'usuari"
                }
            }
        }
    },
    "exceptions": {
        "config_entry_error_missing_internal_url": {
            "message": "Assegura't que Home Assistant tingui un URL intern v\u00e0lid"
        }
    }
}